# Generated by Django 2.2 on 2019-06-24 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=150, db_index=True)),
                ('profile_picture', models.CharField(max_length=1024)),
                ('access_token', models.CharField(max_length=150)),
                ('token_expires_in', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'authentication_oauth_users',
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
    ]
